### ISSUE TITLE
Error: [node-persist][readFile] does not look like a valid storage file!

### ISSUE THREAD

**Issue by gideontong** [gideontong/Amy#13]
Console spam is causing the following error:

```bash
at /node_modules/node-persist/src/local-storage.js:314:89
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:112445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: ID)
```

The root cause of this is unknown, but it is known that this specific error is caused by *incorrect formatting of the JSON file in question*. It may be possible to simply use a try-catch block to catch this error and start a sanitization script to fix the offending file before resuming work. This is more of a band-aid solution than a real solution, but it may help alleviate issues.

**Comment by gideontong** [comment]
It's caused by writing twice to the same file in different processes. Some solutions can involve switching to SQL or using a queue to monitor tasks.

**Comment by gideontong** [comment]
Closing due to expiration and rewrite that will likely fix this issue.
